[file]
    [file.app]
    fileName = "./logs/app.log"
    daily = true
    maxDays = 30
    rotate = true
    level = 9
    perm = "0744"

    [file.for_debug]
    fileName = "./logs/for_debug.log"
    daily = true
    maxDays = 30
    rotate = true
    level = 6
    perm = "0744"

    [file.access]
    fileName = "./logs/access.log"
    daily = true
    hourly = true
    maxHours = 168
    rotate = true
    level = 6
    perm = "0744"
